### ISSUE TITLE
Usage of ingress controller level wildcard certificat

### ISSUE THREAD

**Issue by jfv-opensource** [OCSInventory-NG/helm-charts#5]
Dear,

the current version of the helm force to create a specific secret in the ocs inventory namespace to store the http certificate. It may be a good idea to allow usage of the ingress controller level certificate. In the common helms, a secret name field is present but if not filled, secret is not created and ingress not references it.

Many thanks,

BR,
jfv

PS: I can contribute

**Comment by gillesdubois** [comment]
Hello,

Your idea is really interesting and is a closer fit to the good practices on helm charts.
Its something we definitely missed out when pushing the first release.

If you want to contribute, we will be glad to review your pull request and welcome you as a contributor :) 

Regards,
Gilles DUBOIS.

**Comment by jfv-opensource** [comment]
I'm on it, Will propose mr soon.

**Comment by gillesdubois** [comment]
You're welcome ! I remain available if you have any questions :)

**Comment by jfv-opensource** [comment]
MR: #6

**Comment by jfv-opensource** [comment]
The change is commited

**Comment by gillesdubois** [comment]
I'm closing this issue, fixed with #6
